# Generated by Django 3.0.6 on 2020-05-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cLatitude', models.CharField(max_length=25, null=True)),
                ('cLongitude', models.CharField(max_length=25, null=True)),
                ('iPostCode', models.PositiveIntegerField(null=True)),
                ('cCountry', models.CharField(max_length=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='weatherAPIForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=25)),
                ('cAdress', models.CharField(max_length=100)),
                ('cKey', models.CharField(max_length=50)),
                ('iCallsPerDay', models.PositiveIntegerField()),
                ('iMaxCallsPerday', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='weatherDayForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dForecasteDate', models.DateTimeField()),
                ('dCallDate', models.DateTimeField()),
                ('cName', models.CharField(max_length=25)),
                ('cIcon', models.CharField(max_length=25)),
                ('mAPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.weatherAPIForecast')),
            ],
        ),
        migrations.CreateModel(
            name='weatherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iMax', models.DecimalField(decimal_places=1, max_digits=3)),
                ('iMin', models.DecimalField(decimal_places=1, max_digits=3)),
                ('iAvg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('iProbability', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cUnit', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='weatherdayforecast',
            name='mHourSun',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunDetail', to='hello.weatherDetail'),
        ),
        migrations.AddField(
            model_name='weatherdayforecast',
            name='mRain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rainDetail', to='hello.weatherDetail'),
        ),
        migrations.AddField(
            model_name='weatherdayforecast',
            name='mTemp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tempDetail', to='hello.weatherDetail'),
        ),
        migrations.AddField(
            model_name='weatherdayforecast',
            name='mWind',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='windDetail', to='hello.weatherDetail'),
        ),
    ]
