# Generated by Django 3.0.6 on 2020-06-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200528_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='iPostCode',
        ),
    ]
