# Generated by Django 3.0.6 on 2020-06-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_email_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
